export type Brother = {
  name: string;
  src: string;
  alt: string;
  role?: string;
  hometown?: string;
  major?: string;
};

export type Class = {
  symbol: string;
  brothers: Brother[];
};

export const execBoard: Brother[] = [
  {
    name: 'Etienne Groom',
    role: 'President',
    src: '/composites/332groom.jpg',
    alt: 'Groom',
  },
  {
    name: 'Gaurav Koratagere',
    role: 'Vice President',
    src: '/composites/335koratagere.jpg',
    alt: 'Koratagere',
  },
  {
    name: 'Carter Olson',
    role: 'VP of Standards',
    src: '/composites/340olson.jpg',
    alt: 'Olson',
  },
  {
    name: 'Andre Chung',
    role: 'VP of Brotherhood',
    src: '/composites/888chung.jpg',
    alt: 'Chung',
  },
  {
    name: 'Jack Silano',
    role: 'VP of Community',
    src: '/composites/898silano.jpg',
    alt: 'Silano',
  },
  {
    name: 'Griffin Wright',
    role: 'VP of Finance',
    src: '/composites/326wright.jpg',
    alt: 'Wright',
  },
  {
    name: 'Vedant Gupta',
    role: 'VP of Risk Management',
    src: '/composites/890gupta.jpg',
    alt: 'Gupta',
  },
  {
    name: 'Noel Burra',
    role: 'Secretary',
    src: '/composites/329burra-noel.jpeg',
    alt: 'Burra',
  },
  {
    name: 'Quinn Miller',
    role: 'Phikeia Educator',
    src: '/composites/894miller.jpg',
    alt: 'Miller',
  },
  {
    name: 'Matthew Kropelnicki',
    role: 'VP of Socials',
    src: '/composites/891kropelnicki.jpg',
    alt: 'Kropelnicki',
  },
  {
    name: 'Enzo Monteiro',
    role: 'VP of Socials',
    src: '/composites/895monteiro.jpg',
    alt: 'Monteiro',
  },
];

export const council: Brother[] = [
  {
    name: 'Daniel Ciejek',
    role: 'Warden',
    src: '/composites/303ciejek.jpg',
    alt: 'Ciejek',
  },
  {
    name: 'Dante Maravell',
    role: 'Chaplain',
    src: '/composites/339maravell.jpg',
    alt: 'Maravell',
  },
  {
    name: 'Matt Lawson',
    role: 'Scholarship Chairman',
    src: '/composites/336lawson.jpg',
    alt: 'Lawson',
  },
  {
    name: 'Ellis McConnell',
    role: 'Chorister',
    src: '/composites/893mcconnell.jpg',
    alt: 'McConnell',
  },
  {
    name: 'Jack Curtin',
    role: 'Philanthropy Chairman',
    src: '/composites/987curtin.png',
    alt: 'Curtin',
  },
  {
    name: 'Andrew Behr',
    role: 'Community Service Chairman',
    src: '/composites/986behr.JPG',
    alt: 'Behr',
  },
  {
    name: 'Charlie Milward',
    role: 'SVP Chairman',
    src: '/composites/995milward.JPG',
    alt: 'Milward',
  },
  {
    name: 'Andrew Stanger',
    role: 'DEI Chairman',
    src: '',
    alt: 'Stanger',
  },
  {
    name: 'Mitchell Petrecca',
    role: 'Recruitment Co-Chairman',
    src: '/composites/341petrecca.jpg',
    alt: 'Petrecca',
  },
  {
    name: 'Jack Haythorn',
    role: 'Recruitment Co-Chairman',
    src: '/composites/319haythorn.jpg',
    alt: 'Haythorn',
  },
  {
    name: 'Konstantin Miebach',
    role: 'Public Relations Chairman',
    src: '/composites/994miebach.png',
    alt: 'Miebach',
  },
  {
    name: 'Saket Kalidindi',
    role: 'Housing Chairman',
    src: '',
    alt: 'Kalidindi',
  },
  {
    name: 'Anthony Abbott',
    role: 'Awards Chairman',
    src: '/composites/884abbott.jpg',
    alt: 'Abbott',
  },
  {
    name: 'Nathan Lothian',
    role: 'Merchandise Chairman',
    src: '/composites/993lothian.png',
    alt: 'Lothian',
  },
];

export const classes: Class[] = [
  {
    symbol: 'AB',
    brothers: [
      {
        name: 'Leo Wu',
        src: '',
        alt: 'Wu',
        hometown: 'Chester Springs, PA',
        major: 'Computer Science & Business',
      },
      {
        name: 'Sameer Wadhwa',
        src: '/composites/1000wadhwa.JPG',
        alt: 'Wadhwa',
        hometown: 'Basking Ridge, NJ',
        major: 'Business Admin',
      },
      {
        name: 'Ryan Suri',
        src: '/composites/999suri.png',
        alt: 'Suri',
        hometown: 'Alamo, CA',
        major: 'Electrical Engineering',
      },
      {
        name: 'Andrew Stanger',
        src: '',
        alt: 'Stanger',
        hometown: 'Portola Valley, CA',
        major: 'Spanish',
      },
      {
        name: 'Shlok Pradip',
        src: '/composites/997pradip.JPG',
        alt: 'Pradip',
        hometown: 'Parker, CO',
        major: 'Computer Science & Math',
      },
      {
        name: 'Anriv Nakirkanti',
        src: '/composites/996nakirkanti.JPG',
        alt: 'Nakirkanti',
        hometown: 'Malvern, PA',
        major: 'Data Science & Business',
      },
      {
        name: 'Charlie Milward',
        src: '/composites/995milward.JPG',
        alt: 'Milward',
        hometown: 'Larchmont, NY',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Konstantin Miebach',
        src: '/composites/994miebach.png',
        alt: 'Miebach',
        hometown: 'Neuburg am Inn, DEU',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Nathan Lothian',
        src: '/composites/993lothian.png',
        alt: 'Lothian',
        hometown: 'Harrison, NY',
        major: 'Electrical Engineering',
      },
      {
        name: 'Lance Leung',
        src: '/composites/992leung.JPG',
        alt: 'Leung',
        hometown: 'Pasadena, CA',
        major: 'Computer Science & Business',
      },
      {
        name: 'Cameron Kraus',
        src: '/composites/991kraus.JPG',
        alt: 'Kraus',
        hometown: 'Los Angeles, CA',
        major: 'Business Administration',
      },
      {
        name: 'Saket Kalidindi',
        src: '',
        alt: 'Kalidindi',
        hometown: 'Dallas, TX',
        major: 'Finance',
      },
      {
        name: 'Abhi Gundala',
        src: '',
        alt: 'Gundala',
        hometown: 'Bellevue, WA',
        major: 'Business Administration',
      },
      {
        name: 'Adrian Edson',
        src: '/composites/988edson.JPG',
        alt: 'Edson',
        hometown: 'Bethesda, MD',
        major: 'Health Science & Pre-Med',
      },
      {
        name: 'Jack Curtin',
        src: '/composites/987curtin.png',
        alt: 'Curtin',
        hometown: 'North Andover, MA',
        major: 'International Business',
      },
      {
        name: 'Andrew Behr',
        src: '/composites/986behr.JPG',
        alt: 'Behr',
        hometown: 'Woodbridge, CT',
        major: 'Economics & International Affairs',
      },
      {
        name: 'Enkidu Bazua-Kelley',
        src: '/composites/985bazua-kelley.png',
        alt: 'Bazua-Kelley',
        hometown: 'Berkeley, CA',
        major: 'Political Science & Economics',
      },
      {
        name: 'Rohin Ariff',
        src: '/composites/984ariff.JPG',
        alt: 'Ariff',
        hometown: 'Needham, MA',
        major: 'Finance & Corporate Innovation',
      },
      {
        name: 'Taj Apparao',
        src: '',
        alt: 'Apparao',
        hometown: 'San Mateo, CA',
        major: 'Environmental Science & Economics',
      },
      {
        name: 'Bryce Akroyd',
        src: '/composites/982akroyd.png',
        alt: 'Akroyd',
        hometown: 'Lenox, MA',
        major: 'Business Admin & Law',
      },
    ],
  },
  {
    symbol: 'AA',
    brothers: [
      {
        name: 'Jack Whalen',
        src: '/composites/899whalen.jpg',
        alt: 'Whalen',
        hometown: 'Dallas, TX',
        major: 'Finance',
      },
      {
        name: 'Jack Silano',
        src: '/composites/898silano.jpg',
        alt: 'Silano',
        hometown: 'Southington, CT',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Nate Pearce',
        src: '/composites/897pearce.jpg',
        alt: 'Pearce',
        hometown: 'Durham, NC',
        major: 'Health Science',
      },
      {
        name: 'Adam Ochoa',
        src: '/composites/896ochoa.jpg',
        alt: 'Ochoa',
        hometown: 'Roslyn Heights, NY',
        major: 'Computer Science & Business',
      },
      {
        name: 'Enzo Monteiro',
        src: '/composites/895monteiro.jpg',
        alt: 'Monteiro',
        hometown: 'New York, NY',
        major: 'Finance & Supply Chain',
      },
      {
        name: 'Quinn Miller',
        src: '/composites/894miller.jpg',
        alt: 'Miller',
        hometown: 'Harvard, MA',
        major: 'Economics & Finance',
      },
      {
        name: 'Ethan Menezes',
        src: '/composites/892menezes.jpg',
        alt: 'Menezes',
        hometown: 'West Chester, PA',
        major: 'Business & Math',
      },
      {
        name: 'Ellis McConnell',
        src: '/composites/893mcconnell.jpg',
        alt: 'McConnell',
        hometown: 'Burlingame, CA',
        major: 'Economics & Business',
      },
      {
        name: 'Matthew Kropelnicki',
        src: '/composites/891kropelnicki.jpg',
        alt: 'Kropelnicki',
        hometown: 'Novato, CA',
        major: 'Economics & Fintech',
      },
      {
        name: 'Landon Jones',
        src: '/composites/889jones.jpg',
        alt: 'Jones',
        hometown: 'Cumberland, ME',
        major: 'Finance',
      },
      {
        name: 'Vedant Gupta',
        src: '/composites/890gupta.jpg',
        alt: 'Gupta',
        hometown: 'Palo Alto, CA',
        major: 'Data Science',
      },
      {
        name: 'Andre Chung',
        src: '/composites/888chung.jpg',
        alt: 'Chung',
        hometown: 'San Francisco, CA',
        major: 'Electrical Engineering',
      },
      {
        name: 'Noah Burra',
        src: '/composites/887burra.jpg',
        alt: 'Burra',
        hometown: 'Ridgefield, CT',
        major: 'Data Science & Neuroscience',
      },
      {
        name: 'Nic Benoit',
        src: '/composites/886benoit.JPG',
        alt: 'Benoit',
        hometown: 'Southbridge, MA',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Gio Amador',
        src: '/composites/885amador.jpg',
        alt: 'Amador',
        hometown: 'Los Angeles, CA',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Anthony Abbott',
        src: '/composites/884abbott.jpg',
        alt: 'Abbott',
        hometown: 'Burlington, MA',
        major: 'Architecture',
      },
    ],
  },
  {
    symbol: 'Ω',
    brothers: [
      {
        name: 'Vivek Singh',
        src: '/composites/343singh.jpg',
        alt: 'Singh',
        hometown: 'Ardsley, NY',
        major: 'Communications & Design',
      },
      {
        name: 'Max Schaefer',
        src: '/composites/342schaefer-m.jpg',
        alt: 'Schaefer',
        hometown: 'Bethesda, MD',
        major: 'Finance',
      },
      {
        name: 'Mitchell Petrecca',
        src: '/composites/341petrecca.jpg',
        alt: 'Petrecca',
        hometown: 'Fairfield, CT',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Carter Olson',
        src: '/composites/340olson.jpg',
        alt: 'Olson',
        hometown: 'Queensbury, NY',
        major: 'International Business & Affairs',
      },
      {
        name: 'Dante Maravell',
        src: '/composites/339maravell.jpg',
        alt: 'Maravell',
        hometown: 'Bethel, ME',
        major: 'Finance',
      },
      {
        name: 'Brad Lyon',
        src: '/composites/338lyon-b.jpg',
        alt: 'Lyon',
        hometown: 'Upton, MA',
        major: 'Architecture',
      },
      {
        name: 'Justin Liao',
        src: '/composites/337liao-2.jpg',
        alt: 'Liao',
        hometown: 'Hsinchu, Taiwan',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Matt Lawson',
        src: '/composites/336lawson.jpg',
        alt: 'Lawson',
        hometown: 'Easton, MA',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Gaurav Koratagere',
        src: '/composites/335koratagere.jpg',
        alt: 'Koratagere',
        hometown: 'Manalapan, NJ',
        major: 'Computer Engineering',
      },
      {
        name: 'Max Kirk',
        src: '/composites/334kirk.jpg',
        alt: 'Kirk',
        hometown: 'Hoboken, NJ',
        major: 'Finance',
      },
      {
        name: 'Etienne Groom',
        src: '/composites/332groom.jpg',
        alt: 'Groom',
        hometown: 'Scotch Plains, NJ',
        major: 'Finance',
      },
      {
        name: 'Jake Eisner',
        src: '/composites/331eisner.jpg',
        alt: 'Eisner',
        hometown: 'Durham, NC',
        major: 'Economics',
      },
      {
        name: 'Nick Cortese',
        src: '/composites/330cortese.jpg',
        alt: 'Cortese',
        hometown: 'Long Island, NY',
        major: 'PR & Marketing',
      },
      {
        name: 'Noel Burra',
        src: '/composites/329burra-noel.jpeg',
        alt: 'Burra',
        hometown: 'Ridgefield, CT',
        major: 'Data Science & Neuroscience',
      },
      {
        name: 'Max Brothers',
        src: '/composites/328brothers.jpeg',
        alt: 'Brothers',
        hometown: 'Baltimore, MD',
        major: 'Political Science',
      },
      {
        name: 'Nathaniel Beland',
        src: '/composites/327beland.jpeg',
        alt: 'Beland',
        hometown: 'Southborough, MA',
        major: 'International Business',
      },
    ],
  },
  {
    symbol: 'Ψ',
    brothers: [
      {
        name: 'Griffin Wright',
        src: '/composites/326wright.jpg',
        alt: 'Wright',
        hometown: 'Dallas, TX',
        major: 'Math & Business',
      },
      {
        name: 'Theo Smith',
        src: '/composites/325smith.jpg',
        alt: 'Smith',
        hometown: 'New York, NY',
        major: 'Fintech',
      },
      {
        name: 'Marco Sciamanda',
        src: '/composites/324sciamanda.jpg',
        alt: 'Sciamanda',
        hometown: 'Lakeville, MN',
        major: 'Economics & Business',
      },
      {
        name: 'Satvik Repaka',
        src: '/composites/323repaka.jpg',
        alt: 'Repaka',
        hometown: 'Watchung, NJ',
        major: 'Computer Science & Business',
      },
      {
        name: 'Mike Pirozzi',
        src: '/composites/322pirozzi.jpg',
        alt: 'Pirozzi',
        hometown: 'Sleepy Hallow, NY',
        major: 'Economics & Environmental Science',
      },
      {
        name: 'Connor Oates',
        src: '/composites/321oates.jpg',
        alt: 'Oates',
        hometown: 'River Vale, NJ',
        major: 'Economics & Business',
      },
      {
        name: 'Jack Haythorn',
        src: '/composites/319haythorn.jpg',
        alt: 'Haythorn',
        hometown: 'Weston, CT',
        major: 'Finance',
      },
      {
        name: 'Andrew Dubanowitz',
        src: '/composites/318dubanowitz-a.jpg',
        alt: 'Dubanowitz',
        hometown: 'Ashland, MA',
        major: 'Finance & Data Science',
      },
      {
        name: 'Oliver Cooke',
        src: '/composites/317cooke.jpg',
        alt: 'Cooke',
        hometown: 'Stonington, CT',
        major: 'Finance',
      },
      {
        name: 'Dan Cibbarelli',
        src: '/composites/316cibbarelli.jpg',
        alt: 'Cibbarelli',
        hometown: 'Princeton, NJ',
        major: 'Finance',
      },
      {
        name: 'Tej Chakravarthy',
        src: '/composites/315chakravarthy.jpg',
        alt: 'Chakravarthy',
        hometown: 'Ellington, CT',
        major: 'Computer Science',
      },
    ],
  },
  {
    symbol: 'Χ',
    brothers: [
      {
        name: 'Justin Zahler',
        src: '/composites/314zahler.jpg',
        alt: 'Zahler',
        hometown: 'Greensboro, GA',
        major: 'Data Science',
      },
      {
        name: 'Grey Vachon',
        src: '/composites/313vachon.jpg',
        alt: 'Vachon',
        hometown: 'Barrington, RI',
        major: 'Management & Family Business',
      },
      {
        name: 'Aiden Sprole',
        src: '/composites/312sprole.jpg',
        alt: 'Sprole',
        hometown: 'Wichita, KS',
        major: 'Journalism',
      },
      {
        name: 'Ben Irvine',
        src: '/composites/309irvine.jpg',
        alt: 'Irvine',
        hometown: 'Los Gatos, CA',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Bobby Goyette',
        src: '/composites/308goyette.jpg',
        alt: 'Goyette',
        hometown: 'Hudson, MA',
        major: 'Biological Engineering',
      },
      {
        name: 'Andreas Gesser',
        src: '/composites/307gesser.jpg',
        alt: 'Gesser',
        hometown: 'Westfield, NJ',
        major: 'Business & Math',
      },
      {
        name: 'Zach Ferdico',
        src: '/composites/306ferdico.jpg',
        alt: 'Ferdico',
        hometown: 'Mountain Lakes, NJ',
        major: 'Business & Marketing',
      },
      {
        name: 'Reece DiGiacomo',
        src: '/composites/305digiacomo.jpg',
        alt: 'DiGiacomo',
        hometown: 'Boulder, CO',
        major: 'Computer Science & Math',
      },
      {
        name: 'Ashton Daniels',
        src: '/composites/304daniels.jpg',
        alt: 'Daniels',
        hometown: 'Chatham, MA',
        major: 'Industrial Engineering',
      },
      {
        name: 'Daniel Ciejek',
        src: '/composites/303ciejek.jpg',
        alt: 'Ciejek',
        hometown: 'Lee, MA',
        major: 'Computer Science',
      },
      {
        name: 'Alexander Au',
        src: '/composites/302au.jpg',
        alt: 'Au',
        hometown: 'Palo Alto, CA',
        major: 'Business Administration',
      },
    ],
  },
  {
    symbol: 'Φ',
    brothers: [
      {
        name: 'Andrew Ow',
        src: '/composites/299ow.jpg',
        alt: 'Ow',
        hometown: 'San Francisco, CA',
        major: 'Business',
      },
      {
        name: 'Diego Klish',
        src: '/composites/297klish.jpg',
        alt: 'Klish',
        hometown: 'Lawrence, KS',
        major: 'Computer Engineering',
      },
      {
        name: 'James Jankunas',
        src: '/composites/295jankunas.jpg',
        alt: 'Jankunas',
        hometown: 'Dover, ME',
        major: 'Mechanical Engineering',
      },
      {
        name: 'Teddy Gray',
        src: '/composites/293gray.jpg',
        alt: 'Gray',
        hometown: 'Ipswich, MA',
        major: 'International Affairs & Economics',
      },
      {
        name: 'Kirk Chayevsky',
        src: '/composites/285chayevsky.jpg',
        alt: 'Chayevsky',
        hometown: 'Atlanta, GA',
        major: 'Entrepreneurship',
      },
    ],
  },
];
